spring.application.name=atm-transaction-management-system

# server port
server.port=8080

# PostgreSQL Database Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/atm_transaction_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configurations
#Used to sign and verify JWT token
jwt.secret=${JWT_SECRET}

# Token validity time in milliseconds 86400000ms = 24 hours
jwt.expiration=86400000